### ISSUE TITLE
Any way to reset / remove items

### ISSUE THREAD

**Issue by LukaJankovic** [MitchellMalleo/MMParallaxPresenter#1]
Is there like an "official" way to reset the presenter? I tried calling "setupPresenter", but it left me with a lot of space at the bottom.

**Comment by MitchellMalleo** [comment]
Hey Jom4nJI,

Yeah setupPresenter was created to setup the backend data structures and other miscellaneous properties, so it makes sense that you're having this issue. I just pushed a new version of the MMParallaxPresenter subclass that has a resetPresenter utility method that should reset your presenter (removes all subviews, scrolls presenter to top, and resets the content size to zero). All you'll have to do in your code is call [self.mmParallaxPresenter resetPresenter]; before passing in a new array of pages and then you should be good to go. (:

**Comment by LukaJankovic** [comment]
Hey, thanks for the quick fix!!
