### ISSUE TITLE
README Typo

### ISSUE THREAD

**Issue by xemacobra** [MitchellMalleo/MMParallaxPresenter#3]
In the README, which was originally copied from your other repo, you forgot to change the name of the pod from **VAProgressCircle** to **MMParallaxPresenter**.

P.S.: Both controls are really nice. Great job. Thanks

**Comment by MitchellMalleo** [comment]
XemaCobra,

Firstly, thank you for your kind words. I'm glad you like them. (:

Good catch on the typo. I'll update the typo and close this issue shortly.
